# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 766ad771a8b19666c5776c2c1ce8602005b04b9f55ee88a09ddefdc0c36755c45b5a6271bc513ab7b4aee98850ec71d3bb606e7e73d002a7430e959b5384228e

test:
  secret_key_base: 677310a3fe91e3d14dec5137de77cabc82ad4fb431ba136974e8514ce387e2c4b4f28ecfd23b7c782297d40818df8fe7fa93cafccff81a2c9028f18f0c74f5ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
